import uuid
from datetime import datetime
from typing import Optional, List
from sqlalchemy import (
    create_engine,
    Column,
    String,
    Text,
    Boolean,
    Integer,
    Float,
    DateTime,
    ForeignKey,
    ARRAY,
    Index,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import declarative_base, relationship, sessionmaker, Session
from pgvector.sqlalchemy import Vector
from config import get_settings

settings = get_settings()

engine = create_engine(settings.database_url)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


class Project(Base):
    __tablename__ = "projects"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False)
    client = Column(String(255))
    site_address = Column(Text)
    status = Column(String(50), default="draft")  # draft, live, closed
    persona_prompt = Column(Text)
    welcome_message = Column(Text, default="Hello! I'm here to help answer your questions about this development proposal. What would you like to know?")
    disclaimer = Column(Text, default="This response is generated by an AI assistant based on published consultation materials. For detailed queries, please contact the consultation team.")
    fallback_message = Column(Text, default="I don't have enough information to answer that question accurately. Please contact our team directly for assistance.")
    contact_email = Column(String(255))
    blocked_topics = Column(ARRAY(String), default=[])
    widget_config = Column(JSONB, default={})
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    documents = relationship("Document", back_populates="project", cascade="all, delete-orphan")
    chunks = relationship("Chunk", back_populates="project", cascade="all, delete-orphan")
    manual_qas = relationship("ManualQA", back_populates="project", cascade="all, delete-orphan")
    conversations = relationship("Conversation", back_populates="project", cascade="all, delete-orphan")


class Document(Base):
    __tablename__ = "documents"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    filename = Column(String(255), nullable=False)
    original_filename = Column(String(255))
    file_type = Column(String(50))  # pdf, docx, txt
    content_type = Column(String(50), default="public")  # public, internal
    upload_date = Column(DateTime, default=datetime.utcnow)
    processed = Column(Boolean, default=False)
    processing_error = Column(Text)
    page_count = Column(Integer)
    tags = Column(ARRAY(String), default=[])

    # Relationships
    project = relationship("Project", back_populates="documents")
    chunks = relationship("Chunk", back_populates="document", cascade="all, delete-orphan")


class Chunk(Base):
    __tablename__ = "chunks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_id = Column(UUID(as_uuid=True), ForeignKey("documents.id", ondelete="CASCADE"))
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    content = Column(Text, nullable=False)
    page_number = Column(Integer)
    chunk_index = Column(Integer)
    token_count = Column(Integer)
    embedding = Column(Vector(1536))
    chunk_metadata = Column(JSONB, default={})
    source_type = Column(String(50), default="document")  # document, url, manual
    source_url = Column(Text)

    # Relationships
    document = relationship("Document", back_populates="chunks")
    project = relationship("Project", back_populates="chunks")


# Create index for vector similarity search
Index(
    "chunks_embedding_idx",
    Chunk.embedding,
    postgresql_using="ivfflat",
    postgresql_with={"lists": 100},
    postgresql_ops={"embedding": "vector_cosine_ops"},
)


class ManualQA(Base):
    __tablename__ = "manual_qa"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    keywords = Column(ARRAY(String), default=[])
    priority = Column(Integer, default=0)
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="manual_qas")


class Conversation(Base):
    __tablename__ = "conversations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    session_id = Column(String(255), nullable=False)
    started_at = Column(DateTime, default=datetime.utcnow)
    user_agent = Column(Text)
    ip_hash = Column(String(64))

    # Relationships
    project = relationship("Project", back_populates="conversations")
    messages = relationship("Message", back_populates="conversation", cascade="all, delete-orphan")


class Message(Base):
    __tablename__ = "messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    conversation_id = Column(UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False)
    role = Column(String(20), nullable=False)  # user, assistant
    content = Column(Text, nullable=False)
    retrieved_chunk_ids = Column(ARRAY(UUID(as_uuid=True)), default=[])
    confidence_score = Column(Float)
    feedback = Column(String(20))  # helpful, not_helpful
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    conversation = relationship("Conversation", back_populates="messages")
    flagged_question = relationship("FlaggedQuestion", back_populates="message", uselist=False)


class FlaggedQuestion(Base):
    __tablename__ = "flagged_questions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    message_id = Column(UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    reason = Column(String(100))  # low_confidence, no_context, sensitive_topic
    resolved = Column(Boolean, default=False)
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    message = relationship("Message", back_populates="flagged_question")


# ============================================================================
# NEW: User Management & Authentication
# ============================================================================

class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String(255), unique=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    name = Column(String(255), nullable=False)
    role = Column(String(50), default="member")  # super_admin, account_manager, member, client, approver
    is_active = Column(Boolean, default=True)
    last_login = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project_memberships = relationship("ProjectMember", back_populates="user", cascade="all, delete-orphan")
    assigned_queries = relationship("Query", foreign_keys="Query.assigned_to", back_populates="assignee")
    created_responses = relationship("QueryResponse", back_populates="created_by_user")
    approvals = relationship("Approval", back_populates="approver")
    activity_logs = relationship("ActivityLog", back_populates="user")


class ProjectMember(Base):
    __tablename__ = "project_members"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    role = Column(String(50), default="member")  # manager, member, client, approver
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="members")
    user = relationship("User", back_populates="project_memberships")


# ============================================================================
# NEW: Widget System
# ============================================================================

class Widget(Base):
    __tablename__ = "widgets"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    type = Column(String(50), nullable=False)  # chatbot, sitemap, comparison, documents, faq, timeline, form, gallery, stats
    name = Column(String(255), nullable=False)
    config = Column(JSONB, default={})
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="widgets")
    faqs = relationship("FAQ", back_populates="widget", cascade="all, delete-orphan")
    timeline_items = relationship("TimelineItem", back_populates="widget", cascade="all, delete-orphan")
    gallery_items = relationship("GalleryItem", back_populates="widget", cascade="all, delete-orphan")
    form_submissions = relationship("Query", back_populates="widget")


class FAQ(Base):
    __tablename__ = "faqs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    widget_id = Column(UUID(as_uuid=True), ForeignKey("widgets.id", ondelete="CASCADE"), nullable=False)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    category = Column(String(100))
    sort_order = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)
    view_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    widget = relationship("Widget", back_populates="faqs")
    project = relationship("Project", back_populates="faqs")


class TimelineItem(Base):
    __tablename__ = "timeline_items"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    widget_id = Column(UUID(as_uuid=True), ForeignKey("widgets.id", ondelete="CASCADE"), nullable=False)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text)
    details = Column(Text)
    date = Column(DateTime, nullable=False)
    end_date = Column(DateTime)
    status = Column(String(50), default="upcoming")  # completed, in-progress, upcoming
    sort_order = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    widget = relationship("Widget", back_populates="timeline_items")
    project = relationship("Project", back_populates="timeline_items")


class GalleryItem(Base):
    __tablename__ = "gallery_items"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    widget_id = Column(UUID(as_uuid=True), ForeignKey("widgets.id", ondelete="CASCADE"), nullable=False)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    type = Column(String(50), default="image")  # image, video
    url = Column(Text, nullable=False)
    thumbnail_url = Column(Text)
    title = Column(String(255))
    caption = Column(Text)
    category = Column(String(100))
    sort_order = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    widget = relationship("Widget", back_populates="gallery_items")
    project = relationship("Project", back_populates="gallery_items")


# ============================================================================
# NEW: Stakeholder Query Tracker
# ============================================================================

class QueryCategory(Base):
    __tablename__ = "query_categories"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(100), nullable=False)
    color = Column(String(20), default="#6b7280")
    sort_order = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="query_categories")
    queries = relationship("Query", back_populates="category")


class Query(Base):
    """Stakeholder queries/feedback submissions"""
    __tablename__ = "queries"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    widget_id = Column(UUID(as_uuid=True), ForeignKey("widgets.id", ondelete="SET NULL"))

    # Submitter info
    submitter_name = Column(String(255))
    submitter_email = Column(String(255))
    submitter_phone = Column(String(50))
    submitter_address = Column(Text)

    # Query content
    subject = Column(String(500))
    content = Column(Text, nullable=False)
    submission_data = Column(JSONB, default={})  # Additional form fields
    attachments = Column(ARRAY(String), default=[])

    # Status and workflow
    status = Column(String(50), default="new")  # new, in_progress, awaiting_approval, approved, sent, closed
    priority = Column(String(20), default="medium")  # low, medium, high, urgent
    category_id = Column(UUID(as_uuid=True), ForeignKey("query_categories.id", ondelete="SET NULL"))
    assigned_to = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"))
    tags = Column(ARRAY(String), default=[])

    # Metadata
    source = Column(String(50), default="form")  # form, email, phone, in_person
    ip_hash = Column(String(64))
    user_agent = Column(Text)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="queries")
    widget = relationship("Widget", back_populates="form_submissions")
    category = relationship("QueryCategory", back_populates="queries")
    assignee = relationship("User", foreign_keys=[assigned_to], back_populates="assigned_queries")
    responses = relationship("QueryResponse", back_populates="query", cascade="all, delete-orphan")
    notes = relationship("QueryNote", back_populates="query", cascade="all, delete-orphan")


class QueryNote(Base):
    """Internal notes on queries"""
    __tablename__ = "query_notes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    query_id = Column(UUID(as_uuid=True), ForeignKey("queries.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"))
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    query = relationship("Query", back_populates="notes")


class QueryResponse(Base):
    """Draft and sent responses to queries"""
    __tablename__ = "query_responses"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    query_id = Column(UUID(as_uuid=True), ForeignKey("queries.id", ondelete="CASCADE"), nullable=False)
    content = Column(Text, nullable=False)
    version = Column(Integer, default=1)
    status = Column(String(50), default="draft")  # draft, pending_approval, approved, sent
    created_by = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"))
    sent_at = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    query = relationship("Query", back_populates="responses")
    created_by_user = relationship("User", back_populates="created_responses")
    approvals = relationship("Approval", back_populates="response", cascade="all, delete-orphan")


class ResponseTemplate(Base):
    """Pre-approved response templates"""
    __tablename__ = "response_templates"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(255), nullable=False)
    category = Column(String(100))
    content = Column(Text, nullable=False)
    variables = Column(JSONB, default=[])  # List of placeholder variables
    usage_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="response_templates")


# ============================================================================
# NEW: Approval Workflow System
# ============================================================================

class ApprovalWorkflow(Base):
    __tablename__ = "approval_workflows"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(255), nullable=False)
    description = Column(Text)
    stages = Column(JSONB, default=[])  # Array of stage configs
    is_default = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="approval_workflows")


class Approval(Base):
    __tablename__ = "approvals"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    response_id = Column(UUID(as_uuid=True), ForeignKey("query_responses.id", ondelete="CASCADE"), nullable=False)
    workflow_id = Column(UUID(as_uuid=True), ForeignKey("approval_workflows.id", ondelete="SET NULL"))
    stage_index = Column(Integer, default=0)
    approver_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"))
    status = Column(String(50), default="pending")  # pending, approved, changes_requested, rejected
    comments = Column(Text)
    decided_at = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    response = relationship("QueryResponse", back_populates="approvals")
    approver = relationship("User", back_populates="approvals")


# ============================================================================
# NEW: Activity Logging & Onboarding
# ============================================================================

class ActivityLog(Base):
    __tablename__ = "activity_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"))
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"))
    entity_type = Column(String(50))  # query, response, approval, project, widget
    entity_id = Column(UUID(as_uuid=True))
    action = Column(String(100), nullable=False)  # created, updated, deleted, status_changed, etc.
    details = Column(JSONB, default={})
    ip_address = Column(String(45))
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="activity_logs")


class OnboardingItem(Base):
    __tablename__ = "onboarding_items"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text)
    assigned_to = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"))
    due_date = Column(DateTime)
    completed_at = Column(DateTime)
    completed_by = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"))
    sort_order = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="onboarding_items")


# ============================================================================
# Update Project relationships
# ============================================================================

# Add new relationships to Project model
Project.members = relationship("ProjectMember", back_populates="project", cascade="all, delete-orphan")
Project.widgets = relationship("Widget", back_populates="project", cascade="all, delete-orphan")
Project.faqs = relationship("FAQ", back_populates="project", cascade="all, delete-orphan")
Project.timeline_items = relationship("TimelineItem", back_populates="project", cascade="all, delete-orphan")
Project.gallery_items = relationship("GalleryItem", back_populates="project", cascade="all, delete-orphan")
Project.queries = relationship("Query", back_populates="project", cascade="all, delete-orphan")
Project.query_categories = relationship("QueryCategory", back_populates="project", cascade="all, delete-orphan")
Project.response_templates = relationship("ResponseTemplate", back_populates="project", cascade="all, delete-orphan")
Project.approval_workflows = relationship("ApprovalWorkflow", back_populates="project", cascade="all, delete-orphan")
Project.onboarding_items = relationship("OnboardingItem", back_populates="project", cascade="all, delete-orphan")


def init_db():
    """Initialize database tables and pgvector extension."""
    from sqlalchemy import text

    with engine.connect() as conn:
        # Enable pgvector extension
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        conn.commit()

    Base.metadata.create_all(bind=engine)
